/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmptyRouteRouteImport } from './routes/empty-route'
import { Route as IndexRouteImport } from './routes/index'

const EmptyRouteRoute = EmptyRouteRouteImport.update({
  id: '/empty-route',
  path: '/empty-route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empty-route': typeof EmptyRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empty-route': typeof EmptyRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empty-route': typeof EmptyRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empty-route'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empty-route'
  id: '__root__' | '/' | '/empty-route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmptyRouteRoute: typeof EmptyRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/empty-route': {
      id: '/empty-route'
      path: '/empty-route'
      fullPath: '/empty-route'
      preLoaderRoute: typeof EmptyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmptyRouteRoute: EmptyRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
