/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as ThemesRouteImport } from './routes/_themes'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteTemplatesRouteImport } from './routes/_site/templates'
import { Route as ThemesThemesRouteImport } from './routes/_themes/themes'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'
import { Route as BlocksCategoryIdRouteImport } from './routes/blocks/$categoryId'
import { Route as PreviewUiSplatRouteImport } from './routes/preview-ui/$'
import { Route as PreviewUiDemoNavbarRouteImport } from './routes/preview-ui/demo-navbar'
import { Route as DocsComponentsSplatRouteImport } from './routes/_docs/components.$'
import { Route as DocsDocsSplatRouteImport } from './routes/_docs/docs.$'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/_themes',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTemplatesRoute = SiteTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SiteRoute,
} as any)
const ThemesThemesRoute = ThemesThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => ThemesRoute,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksCategoryIdRoute = BlocksCategoryIdRouteImport.update({
  id: '/blocks/$categoryId',
  path: '/blocks/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewUiSplatRoute = PreviewUiSplatRouteImport.update({
  id: '/preview-ui/$',
  path: '/preview-ui/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewUiDemoNavbarRoute = PreviewUiDemoNavbarRouteImport.update({
  id: '/preview-ui/demo-navbar',
  path: '/preview-ui/demo-navbar',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsComponentsSplatRoute = DocsComponentsSplatRouteImport.update({
  id: '/components/$',
  path: '/components/$',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocsSplatRoute = DocsDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/templates': typeof SiteTemplatesRoute
  '/themes': typeof ThemesThemesRoute
  '/blocks/$categoryId': typeof BlocksCategoryIdRoute
  '/preview-ui/$': typeof PreviewUiSplatRoute
  '/preview-ui/demo-navbar': typeof PreviewUiDemoNavbarRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/$': typeof DocsComponentsSplatRoute
  '/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/templates': typeof SiteTemplatesRoute
  '/themes': typeof ThemesThemesRoute
  '/blocks/$categoryId': typeof BlocksCategoryIdRoute
  '/preview-ui/$': typeof PreviewUiSplatRoute
  '/preview-ui/demo-navbar': typeof PreviewUiDemoNavbarRoute
  '/blocks': typeof BlocksIndexRoute
  '/components/$': typeof DocsComponentsSplatRoute
  '/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs': typeof DocsRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_themes': typeof ThemesRouteWithChildren
  '/_site/templates': typeof SiteTemplatesRoute
  '/_themes/themes': typeof ThemesThemesRoute
  '/blocks/$categoryId': typeof BlocksCategoryIdRoute
  '/preview-ui/$': typeof PreviewUiSplatRoute
  '/preview-ui/demo-navbar': typeof PreviewUiDemoNavbarRoute
  '/_site/': typeof SiteIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/_docs/components/$': typeof DocsComponentsSplatRoute
  '/_docs/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates'
    | '/themes'
    | '/blocks/$categoryId'
    | '/preview-ui/$'
    | '/preview-ui/demo-navbar'
    | '/blocks/'
    | '/components/$'
    | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/templates'
    | '/themes'
    | '/blocks/$categoryId'
    | '/preview-ui/$'
    | '/preview-ui/demo-navbar'
    | '/blocks'
    | '/components/$'
    | '/docs/$'
  id:
    | '__root__'
    | '/_docs'
    | '/_site'
    | '/_themes'
    | '/_site/templates'
    | '/_themes/themes'
    | '/blocks/$categoryId'
    | '/preview-ui/$'
    | '/preview-ui/demo-navbar'
    | '/_site/'
    | '/blocks/'
    | '/_docs/components/$'
    | '/_docs/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsRoute: typeof DocsRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  ThemesRoute: typeof ThemesRouteWithChildren
  BlocksCategoryIdRoute: typeof BlocksCategoryIdRoute
  PreviewUiSplatRoute: typeof PreviewUiSplatRoute
  PreviewUiDemoNavbarRoute: typeof PreviewUiDemoNavbarRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_themes': {
      id: '/_themes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/templates': {
      id: '/_site/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof SiteTemplatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_themes/themes': {
      id: '/_themes/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesThemesRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$categoryId': {
      id: '/blocks/$categoryId'
      path: '/blocks/$categoryId'
      fullPath: '/blocks/$categoryId'
      preLoaderRoute: typeof BlocksCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-ui/$': {
      id: '/preview-ui/$'
      path: '/preview-ui/$'
      fullPath: '/preview-ui/$'
      preLoaderRoute: typeof PreviewUiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-ui/demo-navbar': {
      id: '/preview-ui/demo-navbar'
      path: '/preview-ui/demo-navbar'
      fullPath: '/preview-ui/demo-navbar'
      preLoaderRoute: typeof PreviewUiDemoNavbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/components/$': {
      id: '/_docs/components/$'
      path: '/components/$'
      fullPath: '/components/$'
      preLoaderRoute: typeof DocsComponentsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/docs/$': {
      id: '/_docs/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsDocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsComponentsSplatRoute: typeof DocsComponentsSplatRoute
  DocsDocsSplatRoute: typeof DocsDocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsComponentsSplatRoute: DocsComponentsSplatRoute,
  DocsDocsSplatRoute: DocsDocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface SiteRouteChildren {
  SiteTemplatesRoute: typeof SiteTemplatesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteTemplatesRoute: SiteTemplatesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface ThemesRouteChildren {
  ThemesThemesRoute: typeof ThemesThemesRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemesRoute: ThemesThemesRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsRoute: DocsRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  ThemesRoute: ThemesRouteWithChildren,
  BlocksCategoryIdRoute: BlocksCategoryIdRoute,
  PreviewUiSplatRoute: PreviewUiSplatRoute,
  PreviewUiDemoNavbarRoute: PreviewUiDemoNavbarRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
