// @ts-nocheck
import * as __fd_glob_69 from "../content/docs/theme/buttons.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/theme/utilities.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/theme/colors.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/dark-mode.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/installation.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/skills.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/introduction.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/principles.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/theme.mdx?collection=docs"
import * as __fd_glob_60 from "../content/components/combo-box.mdx?collection=components"
import * as __fd_glob_59 from "../content/components/avatar.mdx?collection=components"
import * as __fd_glob_58 from "../content/components/input-time.mdx?collection=components"
import * as __fd_glob_57 from "../content/components/range-calendar.mdx?collection=components"
import * as __fd_glob_56 from "../content/components/multi-select.mdx?collection=components"
import * as __fd_glob_55 from "../content/components/dialog.mdx?collection=components"
import * as __fd_glob_54 from "../content/components/menu.mdx?collection=components"
import * as __fd_glob_53 from "../content/components/search-field.mdx?collection=components"
import * as __fd_glob_52 from "../content/components/switch.mdx?collection=components"
import * as __fd_glob_51 from "../content/components/calendar.mdx?collection=components"
import * as __fd_glob_50 from "../content/components/toggle-group.mdx?collection=components"
import * as __fd_glob_49 from "../content/components/line-chart.mdx?collection=components"
import * as __fd_glob_48 from "../content/components/tracker.mdx?collection=components"
import * as __fd_glob_47 from "../content/components/select.mdx?collection=components"
import * as __fd_glob_46 from "../content/components/input.mdx?collection=components"
import * as __fd_glob_45 from "../content/components/callout.mdx?collection=components"
import * as __fd_glob_44 from "../content/components/checkbox.mdx?collection=components"
import * as __fd_glob_43 from "../content/components/skeleton.mdx?collection=components"
import * as __fd_glob_42 from "../content/components/table.mdx?collection=components"
import * as __fd_glob_41 from "../content/components/native-table.mdx?collection=components"
import * as __fd_glob_40 from "../content/components/separator.mdx?collection=components"
import * as __fd_glob_39 from "../content/components/progress-bar.mdx?collection=components"
import * as __fd_glob_38 from "../content/components/badge.mdx?collection=components"
import * as __fd_glob_37 from "../content/components/sidebar.mdx?collection=components"
import * as __fd_glob_36 from "../content/components/number-field.mdx?collection=components"
import * as __fd_glob_35 from "../content/components/modal.mdx?collection=components"
import * as __fd_glob_34 from "../content/components/text.mdx?collection=components"
import * as __fd_glob_33 from "../content/components/toggle.mdx?collection=components"
import * as __fd_glob_32 from "../content/components/button.mdx?collection=components"
import * as __fd_glob_31 from "../content/components/card.mdx?collection=components"
import * as __fd_glob_30 from "../content/components/slider.mdx?collection=components"
import * as __fd_glob_29 from "../content/components/popover.mdx?collection=components"
import * as __fd_glob_28 from "../content/components/loader.mdx?collection=components"
import * as __fd_glob_27 from "../content/components/tabs.mdx?collection=components"
import * as __fd_glob_26 from "../content/components/pie-chart.mdx?collection=components"
import * as __fd_glob_25 from "../content/components/icon.mdx?collection=components"
import * as __fd_glob_24 from "../content/components/input-otp.mdx?collection=components"
import * as __fd_glob_23 from "../content/components/radio.mdx?collection=components"
import * as __fd_glob_22 from "../content/components/disclosure-group.mdx?collection=components"
import * as __fd_glob_21 from "../content/components/date-picker.mdx?collection=components"
import * as __fd_glob_20 from "../content/components/disclosure.mdx?collection=components"
import * as __fd_glob_19 from "../content/components/navbar.mdx?collection=components"
import * as __fd_glob_18 from "../content/components/area-chart.mdx?collection=components"
import * as __fd_glob_17 from "../content/components/aspect-ratio.mdx?collection=components"
import * as __fd_glob_16 from "../content/components/tag-field.mdx?collection=components"
import * as __fd_glob_15 from "../content/components/index.mdx?collection=components"
import * as __fd_glob_14 from "../content/components/link.mdx?collection=components"
import * as __fd_glob_13 from "../content/components/input-date.mdx?collection=components"
import * as __fd_glob_12 from "../content/components/progress-bar-circle.mdx?collection=components"
import * as __fd_glob_11 from "../content/components/date-range-picker.mdx?collection=components"
import * as __fd_glob_10 from "../content/components/keyboard.mdx?collection=components"
import * as __fd_glob_9 from "../content/components/bar-chart.mdx?collection=components"
import * as __fd_glob_8 from "../content/components/time-picker.mdx?collection=components"
import * as __fd_glob_7 from "../content/components/breadcrumbs.mdx?collection=components"
import * as __fd_glob_6 from "../content/components/alert.mdx?collection=components"
import * as __fd_glob_5 from "../content/components/heading.mdx?collection=components"
import * as __fd_glob_4 from "../content/components/file-trigger.mdx?collection=components"
import * as __fd_glob_3 from "../content/components/chart.mdx?collection=components"
import * as __fd_glob_2 from "../content/components/tag-group.mdx?collection=components"
import * as __fd_glob_1 from "../content/components/sheet.mdx?collection=components"
import * as __fd_glob_0 from "../content/components/drop-zone.mdx?collection=components"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const components = await create.docs("components", "content/components", {}, {"drop-zone.mdx": __fd_glob_0, "sheet.mdx": __fd_glob_1, "tag-group.mdx": __fd_glob_2, "chart.mdx": __fd_glob_3, "file-trigger.mdx": __fd_glob_4, "heading.mdx": __fd_glob_5, "alert.mdx": __fd_glob_6, "breadcrumbs.mdx": __fd_glob_7, "time-picker.mdx": __fd_glob_8, "bar-chart.mdx": __fd_glob_9, "keyboard.mdx": __fd_glob_10, "date-range-picker.mdx": __fd_glob_11, "progress-bar-circle.mdx": __fd_glob_12, "input-date.mdx": __fd_glob_13, "link.mdx": __fd_glob_14, "index.mdx": __fd_glob_15, "tag-field.mdx": __fd_glob_16, "aspect-ratio.mdx": __fd_glob_17, "area-chart.mdx": __fd_glob_18, "navbar.mdx": __fd_glob_19, "disclosure.mdx": __fd_glob_20, "date-picker.mdx": __fd_glob_21, "disclosure-group.mdx": __fd_glob_22, "radio.mdx": __fd_glob_23, "input-otp.mdx": __fd_glob_24, "icon.mdx": __fd_glob_25, "pie-chart.mdx": __fd_glob_26, "tabs.mdx": __fd_glob_27, "loader.mdx": __fd_glob_28, "popover.mdx": __fd_glob_29, "slider.mdx": __fd_glob_30, "card.mdx": __fd_glob_31, "button.mdx": __fd_glob_32, "toggle.mdx": __fd_glob_33, "text.mdx": __fd_glob_34, "modal.mdx": __fd_glob_35, "number-field.mdx": __fd_glob_36, "sidebar.mdx": __fd_glob_37, "badge.mdx": __fd_glob_38, "progress-bar.mdx": __fd_glob_39, "separator.mdx": __fd_glob_40, "native-table.mdx": __fd_glob_41, "table.mdx": __fd_glob_42, "skeleton.mdx": __fd_glob_43, "checkbox.mdx": __fd_glob_44, "callout.mdx": __fd_glob_45, "input.mdx": __fd_glob_46, "select.mdx": __fd_glob_47, "tracker.mdx": __fd_glob_48, "line-chart.mdx": __fd_glob_49, "toggle-group.mdx": __fd_glob_50, "calendar.mdx": __fd_glob_51, "switch.mdx": __fd_glob_52, "search-field.mdx": __fd_glob_53, "menu.mdx": __fd_glob_54, "dialog.mdx": __fd_glob_55, "multi-select.mdx": __fd_glob_56, "range-calendar.mdx": __fd_glob_57, "input-time.mdx": __fd_glob_58, "avatar.mdx": __fd_glob_59, "combo-box.mdx": __fd_glob_60, });

export const docs = await create.docs("docs", "content/docs", {}, {"theme.mdx": __fd_glob_61, "principles.mdx": __fd_glob_62, "introduction.mdx": __fd_glob_63, "skills.mdx": __fd_glob_64, "installation.mdx": __fd_glob_65, "dark-mode.mdx": __fd_glob_66, "theme/colors.mdx": __fd_glob_67, "theme/utilities.mdx": __fd_glob_68, "theme/buttons.mdx": __fd_glob_69, });